//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yien_Express.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.YienExpressWebServiceSoap")]
    public interface YienExpressWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name ncname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertNormalClients", ReplyAction="*")]
        Yien_Express.ServiceReference1.insertNormalClientsResponse insertNormalClients(Yien_Express.ServiceReference1.insertNormalClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertNormalClients", ReplyAction="*")]
        System.Threading.Tasks.Task<Yien_Express.ServiceReference1.insertNormalClientsResponse> insertNormalClientsAsync(Yien_Express.ServiceReference1.insertNormalClientsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertNormalClientsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertNormalClients", Namespace="http://tempuri.org/", Order=0)]
        public Yien_Express.ServiceReference1.insertNormalClientsRequestBody Body;
        
        public insertNormalClientsRequest() {
        }
        
        public insertNormalClientsRequest(Yien_Express.ServiceReference1.insertNormalClientsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertNormalClientsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ncid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ncname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nccontact;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ncnic;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ncaddress;
        
        public insertNormalClientsRequestBody() {
        }
        
        public insertNormalClientsRequestBody(int ncid, string ncname, int nccontact, int ncnic, string ncaddress) {
            this.ncid = ncid;
            this.ncname = ncname;
            this.nccontact = nccontact;
            this.ncnic = ncnic;
            this.ncaddress = ncaddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertNormalClientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertNormalClientsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Yien_Express.ServiceReference1.insertNormalClientsResponseBody Body;
        
        public insertNormalClientsResponse() {
        }
        
        public insertNormalClientsResponse(Yien_Express.ServiceReference1.insertNormalClientsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertNormalClientsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int insertNormalClientsResult;
        
        public insertNormalClientsResponseBody() {
        }
        
        public insertNormalClientsResponseBody(int insertNormalClientsResult) {
            this.insertNormalClientsResult = insertNormalClientsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface YienExpressWebServiceSoapChannel : Yien_Express.ServiceReference1.YienExpressWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YienExpressWebServiceSoapClient : System.ServiceModel.ClientBase<Yien_Express.ServiceReference1.YienExpressWebServiceSoap>, Yien_Express.ServiceReference1.YienExpressWebServiceSoap {
        
        public YienExpressWebServiceSoapClient() {
        }
        
        public YienExpressWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YienExpressWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YienExpressWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YienExpressWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Yien_Express.ServiceReference1.insertNormalClientsResponse Yien_Express.ServiceReference1.YienExpressWebServiceSoap.insertNormalClients(Yien_Express.ServiceReference1.insertNormalClientsRequest request) {
            return base.Channel.insertNormalClients(request);
        }
        
        public int insertNormalClients(int ncid, string ncname, int nccontact, int ncnic, string ncaddress) {
            Yien_Express.ServiceReference1.insertNormalClientsRequest inValue = new Yien_Express.ServiceReference1.insertNormalClientsRequest();
            inValue.Body = new Yien_Express.ServiceReference1.insertNormalClientsRequestBody();
            inValue.Body.ncid = ncid;
            inValue.Body.ncname = ncname;
            inValue.Body.nccontact = nccontact;
            inValue.Body.ncnic = ncnic;
            inValue.Body.ncaddress = ncaddress;
            Yien_Express.ServiceReference1.insertNormalClientsResponse retVal = ((Yien_Express.ServiceReference1.YienExpressWebServiceSoap)(this)).insertNormalClients(inValue);
            return retVal.Body.insertNormalClientsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Yien_Express.ServiceReference1.insertNormalClientsResponse> Yien_Express.ServiceReference1.YienExpressWebServiceSoap.insertNormalClientsAsync(Yien_Express.ServiceReference1.insertNormalClientsRequest request) {
            return base.Channel.insertNormalClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Yien_Express.ServiceReference1.insertNormalClientsResponse> insertNormalClientsAsync(int ncid, string ncname, int nccontact, int ncnic, string ncaddress) {
            Yien_Express.ServiceReference1.insertNormalClientsRequest inValue = new Yien_Express.ServiceReference1.insertNormalClientsRequest();
            inValue.Body = new Yien_Express.ServiceReference1.insertNormalClientsRequestBody();
            inValue.Body.ncid = ncid;
            inValue.Body.ncname = ncname;
            inValue.Body.nccontact = nccontact;
            inValue.Body.ncnic = ncnic;
            inValue.Body.ncaddress = ncaddress;
            return ((Yien_Express.ServiceReference1.YienExpressWebServiceSoap)(this)).insertNormalClientsAsync(inValue);
        }
    }
}
